#
# @lc app=leetcode id=89 lang=python3
#
# [89] Gray Code
#

# @lc code=start
class Solution:
    def grayCode(self, n: int) -> List[int]:
        
        # The total number of gray codes for n bits is 2^n.
        # This can be calculated as 1 shifted left by n positions.
        num_codes = 1 << n
        
        gray_sequence = []
        # The i-th Gray code can be generated by the formula G(i) = i ^ (i >> 1).
        # We iterate from 0 up to (2^n - 1) to generate all n-bit Gray codes.
        for i in range(num_codes):
            gray_sequence.append(i ^ (i >> 1))
            
        return gray_sequence
# @lc code=end
